implementation/MindHive/MindHive/urls.py
# MindHive URL Configuration
# The `urlpatterns` list routes URLs to views.

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views


# urlpatterns to match the urls with the views
urlpatterns = [
    path('', views.HomePage.as_view(), name='index'),          # index page
    path('admin/', admin.site.urls),                           # admin page
    path('questions/', include('questions.urls',
         namespace='questions')),                              # questions app urls
    path('users/', include('users.urls', namespace='users')),  # users app urls
    path('home/', include('home.urls', namespace='home'))      # home app urls
]

# add the media files to the urlpatterns
urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

implementation/MindHive/home/urls.py
from django.urls import path
from . import views


# define the namespace for the below urls
app_name='home'

urlpatterns = [
    path('', views.view, name='view_home'),                              # home page
    path('questions', views.allQuestionsView, name='view_questions'),    # all questions page
    path('search_results', views.search_results, name='search_results'), # search results page
    path('following/', views.folView, name='following'),                 # following page
    path('bookmarks/', views.bookView, name='bookmarks'),                # bookmarks page
    path('tags/<tagname>', views.tagView, name='tags'),                  # tag questions page
    path('authorQuestions', views.autQues, name='authorQuestions'),         # author questions page
    path('<int:user_id>/questions', views.otautQues, name='otherauthorQuestions') ,      # author questions page
]

implementation/MindHive/questions/urls.py
from django.urls import path

from . import views

# namespace for the app
app_name = 'questions'

urlpatterns = [
    # eg: /questions/1/
    path('<int:question_id>', views.view_question,
         name='view_question'),         # view a question
    path('<int:question_id>/edit', views.edit_question,
         name='edit_question'),    # edit a question
    path('askform/', views.QuestionCreateView.as_view(),
         name="add_question"),     # add a question
    # vote on a question/answer
    path('<int:question_id>/vote', views.vote, name='vote'),
    path('follow-bookmark', views.follow_bookmark,
         name='follow_bookmark'),       # follow / bookmark
    # report a question / answer
    path('<int:question_id>/report', views.report, name='report'),
    path('<int:question_id>/add-comment', views.add_comment,
         name='add_comment'),  # add a comment to a question / answer
    path('<int:question_id>/add-answer', views.add_answer,
         name='add_answer'),    # add an answer to a question
]

implementation/MindHive/users/urls.py
# declare the various endpoints of users/
from django.urls import path, include
from .views import UserEditView
from . import views
from django.urls import re_path
from django.contrib.auth import views as auth_views
# from django.conf.urls import re_path

app_name = 'users'

urlpatterns = [
    # eg: /users/1/
    path('', views.testview, name='testview'),
    # path('', include('django.contrib.auth.urls')) ,
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',
        views.signup, name='signup'),
    path('<int:pk>', views.profile, name='view_user'),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html',email_template_name='users/password_reset_email.html',success_url='/users/password_reset_done/'), name='reset_password'),
    path('password_reset_done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_sent.html')),
    path('password_reset_confirm/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_form.html',success_url='/users/password_reset_complete/'), name='password_reset_confirm'),
    path('password_reset_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_done.html')),
    path('edit/', UserEditView.as_view(), name='edit_users'),
    path('addtags/',views.addTagsView.as_view(), name='addtags'),
    path('notifications/', views.notifs_display, name='notifs'),
    path('users/', views.users_list_view, name='users_list'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate')
]

implementation/MindHive/templates/base.html
<!DOCTYPE html>
<html lang="en">

<!-- load static and crispy forms tags -->
{% load static %}
{% load crispy_forms_tags %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- title for the webpage -->
    <title>
        {% block insert_title %}
        Welcome to MindHive
        {% endblock %}
    </title>

    <!-- import bootstrap before any other stylesheet -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- import fontawesome for cool icons -->
    <script src="https://kit.fontawesome.com/1c64b1c074.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- import custom stylesheet -->
    <link href="{% static 'css/master.css'%}" rel="stylesheet" />

    <!-- import jQuery for like/unlike buttons -->
    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

    <!-- import font awesome js -->
    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
        integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ"
        crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
        integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
        crossorigin="anonymous"></script>
</head>


<body id="page-top">
    <!-- top bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <div class="container px-4">
            <!-- MindHive logo -->
            <a href="{% url 'home:view_home'%}" id="logo">
                <img src="{% static 'media/icon.jpg' %}" alt="MindHive" class="logo-img">
            </a>

            <!-- MindHive title -->
            <a class="navbar-brand" href="#page-top">MindHive</a>

            <!-- toggler for navigation bar -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- top navigation bar -->
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <!-- search bar -->
                    <form class="inline-block" method=get action="{% url  'home:search_results' %}">
                        <input class="form-input" type="search" placeholder="Search" aria-placeholder="Search"
                            name="searched" id="search-input">
                        <input type="submit" class="btn btn-fill btn-primary" value=" Search " id="search">
                    </form>

                    <!-- notifications dropdown -->
                    <li class="nav-item">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa-solid fa-bell"></i>
                                {% if user.notifications.count %}
                                <span
                                    class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                                    {{ user.notifications.count }}
                                </span>
                                {% endif %}
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="width: fit-content;">
                                <a class="dropdown-item notif-head" href="#dropdownMenuButton">NOTIFICATIONS</a>
                                {% if user.notifications.count %}
                                {% for notification in user.notifications.all %}
                                <hr style="margin: 0;">
                                <a class="dropdown-item"
                                    href="{% url 'questions:view_question' notification.target_question.id %}">
                                    {{notification.text}} &nbsp; <span class="notif-time">{{notification.timestamp}}
                                        </short>
                                </a>
                                {% endfor %}
                                {% else %}
                                <hr style="margin: 0;">
                                &nbsp; No new notifications &nbsp;
                                {% endif %}
                            </div>
                        </div>
                    </li>

                    <!-- settings dropdown -->
                    <li class="nav-item">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Settings
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="width: fit-content;">
                                {% if user.is_authenticated %}
                                <a class="dropdown-item" href="{% url 'users:edit_users' %}">Edit Your Profile</a>
                                <a class="dropdown-item" href="{% url 'users:reset_password' %}">Change Password</a>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>

                                {% else %}
                                <a class="dropdown-item" href="{% url 'users:login' %}">Login</a>
                                <a class="dropdown-item" href="{% url 'users:signup' %}">Sign Up</a>

                                {% endif %}
                                <a class="dropdown-item" href="mailto:mindhiveiitk@gmail.com">Contact Us</a>
                            </div>
                        </div>
                    </li>
            </div>
        </div>
    </nav>

    <!-- left side bar -->
    <div class='container' id="left">
        <a href="{% url 'home:view_home'%}" class="sect">
            <div class="comp" id="homeButton">
                <i class="fa fa-home"></i>
                &nbsp; Home
            </div>
        </a>
        <a href="{% url 'questions:add_question'%}" class="sect">
            <div class="comp" id="askButton">
                <i class="fa-solid fa-pen-to-square"></i>
                &nbsp; Ask Question
            </div>
        </a>

        <hr color="white" style="border: 0.5px solid rgb(0, 0, 0);" />

        <a href="{% url 'home:view_questions' %}" class="sect">
            <div class="comp" id="questionButton">
                <i class="fa-solid fa-circle-question"></i>
                &nbsp; Questions
            </div>
        </a>

        <a href="{% url 'home:authorQuestions' %}" class="sect">
            <div class="comp" id="questionButton">
                <i class="fa-solid fa-mitten"></i>
                &nbsp; My Questions
            </div>
        </a>

        <a href="{% url 'users:addtags' %}" class="sect">
            <div class="comp" id="tagsButton">
                <i class="fa-solid fa-tags"></i>
                &nbsp; Tags
            </div>
        </a>

        <a href="{% url 'users:users_list' %}" class="sect">
            <div class="comp" id="usersButton">
                <i class="fa-solid fa-users"></i>
                &nbsp; Users
            </div>
        </a>

        <hr color="white" style="border: 0.5px solid rgb(0, 0, 0);" />

        <a href="{%url 'home:following'%}" class="sect">
            <div class="comp" id="followingButton">
                <i class="fa-solid fa-star"></i>
                &nbsp; Following
            </div>
        </a>

        <a href="{%url 'home:bookmarks'%}" class="sect">
            <div class="comp" id="bookmarksButton">
                <i class="fa-solid fa-bookmark"></i>
                &nbsp; Bookmarks
            </div>
        </a>

        <a href="{% url 'users:view_user' user.id%}" class="sect">
            <div class="comp" id="profileButton">
                <i class="fa-solid fa-circle-user"></i>
                &nbsp; View Profile
            </div>
        </a>
    </div>

    <!-- container for the content -->
    <div class="content container">
        {% block insert_content %}
        <!-- ADD CONTENT HERE -->
        {% endblock %}
    </div>

    <!-- right side bar -->
    <div class='container d-flex flex-column h-100' id="right">
        {% block insert_right_bar %}

        {% endblock %}
    </div>

    <!-- bootstrap and popper scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <script>
        $(window).on('load', function () {
            $('.modal.fade').appendTo('body');
        })
    </script>
</body>

</html>

implementation/MindHive/templates/footer.html
{% load static %}

<footer class="py-5 bg-dark" style = 'position: fixed; left: 0; bottom: 0; width: 100%; test-align: center;'>
    <div class="container px-4"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src={% static 'MindHive/js/master.js'%}></script>

implementation/MindHive/templates/homepage.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% load static %}

{% block insert_title %}
{{ usr.name }} - MindHive
{% endblock %}

{%block insert_content%}

<div class="profile">
    <div id="photo">
        <div id="center-photo">
            <img src="{{usr.profile_image.url}}" alt="Image not found" />
        </div>
    </div>
    <div id="data">
        <form class="data-input" action="" view="profile">
            Username<br>
            <x class="test">{{usr.username}}</x>
        </form>
        <p></p>
        <form class="data-input" action="" view="profile">
            Name<br>
            <x class="test">{{usr.name}}</x>
        </form>
        <p></p>
        <form class="data-input" action="" view="profile">
            Email<br>
            <x class="test">{{usr.email}}</x>
        </form>
        <p></p>
        {% if usr == user %}
        <form class="data-input" action="" view="profile">
            <a href="{% url 'home:authorQuestions' %}">Questions Asked</a><br>
        </form>
        {%else%}
        <form class="data-input" action="" view="profile">
            <a href="{% url 'home:otherauthorQuestions' usr.id %}">Questions Asked</a><br>
        </form>
        {% endif %}
    </div>
</div>
</div>
{% if usr == request.user %}
<script>
    $(document).ready(function () {
        $("#profileButton").closest('a').addClass("active");
    })
</script>
{% else %}
<script>
    $(document).ready(function () {
        $("#usersButton").closest('a').addClass("active");
    })
</script>
{% endif %}
{% endblock %}

implementation/MindHive/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Welcome to MindHive</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <link href="{% static 'css/master.css'%}" rel="stylesheet" />
</head>

<body>
    <!-- Header-->
    <header class="text-white" style="background-color: #412c49;">
        <div class="container px-4 text-center">
            <br>
            <h1 class="fw-bolder">
                <a class="title-mindhive" href="{% url 'index' %}" style="color: white;">Welcome to MindHive</a>
            </h1>
            <p class="lead">A QnA platform for the IITK community</p>
            <div class="container">
                {% if user.is_authenticated %}
                <a class="btn btn-lg btn-light" id="logout" href="{% url 'users:logout' %}">Logout</a>
                &nbsp; &nbsp;
                <a class="btn btn-lg btn-light" id="home" href="{% url 'home:view_questions' %}">Home Page</a>
                {% else%}
                <a class="btn btn-lg btn-light" id="signup" href="{% url 'users:signup' %}">Sign Up</a>
                &nbsp; &nbsp;
                <a class="btn btn-lg btn-light" id="signin" href="{% url 'users:login' %}">Sign In</a>
                {% endif %}
            </div>
            <br>
        </div>
    </header>
    <br>
    <!-- About section-->
    <section id="about">
        <div class="container px-4">
            <div class="row gx-4 justify-content-center">
                <div class="col-lg-8">
                    <h2>About our website</h2>
                    <p class="lead">Our website is made using Django and HTML, CSS mainly</p>
                    <p class="lead">It is made under the CS253 course project under the guidance of professor
                        Indranil Saha and our TA Sri Madhan
                    </p>
                    <p class="lead">Our Team includes: Harsh Trivedi, L Gokulnath, Rishav Bikarwar, Ujwal Jyot Panda,
                        Parth Maniar, Adi Pratap Singh, Sahil Bansal, Bhavya Garg, Gavish Garg, Aakash Om Trivedi.
                    </p>
                </div>
            </div>
        </div>
    </section>
    <br>
    <!-- Services section-->
    <section class="bg-light" id="services">
        <div class="container px-4">
            <div class="row gx-4 justify-content-center">
                <div class="col-lg-8">
                    <h2>Services we offer</h2>
                    <p class="lead">We provide a platform where you can ask any query either related to campus,
                        academics, clubs and it also allows interaction between seniors and juniors.</p>
                </div>
            </div>
        </div>
    </section>
    <br>
    <!-- Contact section-->
    <section id="contact">
        <div class="container px-4">
            <div class="row gx-4 justify-content-center">
                <div class="col-lg-8">
                    <h2>Contact us</h2>
                    <p class="lead">For any query mail at:
                        <a href="mailto:mindhiveiitk@gmail.com">mindhiveiitk@gmail.com</a>
                    </p>
                </div>
            </div>
        </div>
    </section>
</body>

</html>

implementation/MindHive/templates/questions_list.html
{% extends 'base.html' %}

{% block insert_title %}
Questions - MindHive
{% endblock %}

{% block insert_content %}
<h1 class="container">
    {% block heading %}
    Questions
    {% endblock %}
</h1>

<br>

<div class="container">

    {% if questions %}
    {%for question in questions%}
    <div class="card d-flex flex-row "
        style="box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset, 0 0 8px rgba(146, 146, 146, 0.6);">

        <!-- question stats -->
        <div class="d-flex flex-column align-middle ques-stats">
            <span>{{question.viewedBy.count}} views</span>
            <span>{{question.get_votes}} votes</span>
            <span>{{question.answer_set.count}} answers</span>
        </div>

        <!-- question content -->
        <div class="d-flex flex-column">
            <!-- question title and summary -->
            <a href="{% url 'questions:view_question' question_id=question.id %}" style="text-decoration: none;">
                <h5 style="margin-bottom: 4px;">{{question.title}}</h5>
            </a>
            <div style="margin-bottom: 4px;">{{question.get_summary_text}}</div>

            <!-- question menu buttons -->
            <div class="d-flex flex-row">
                <span>
                    <!-- bookmark and follow buttons -->
                    <form class="follow-bookmark-form icon-only-buttons" style="display:inline">
                        {% csrf_token %}
                        <input type="hidden" name="question_id" value="{{question.id}}">

                        <button type="submit" class="bookmark" name="action" , value="bookmark" data-toggle="tooltip" data-placement="bottom" title="Bookmark">
                            {% if user in question.users_bookmarked.all %}
                            <i class="fa-solid fa-bookmark"></i>
                            {% else %}
                            <i class="fa-regular fa-bookmark"></i>
                            {% endif %}
                        </button>

                        <button type="submit" class="follow" name="action" , value="follow" data-toggle="tooltip" data-placement="bottom" title="Follow">
                            {% if user in question.users_following.all %}
                            <i class="fa-solid fa-star"></i>
                            {% else %}
                            <i class="fa-regular fa-star"></i>
                            {% endif %}
                        </button>
                    </form>

                    <!-- report button -->
                    {% if not user.blocked %}
                    <!-- Button trigger modal -->
                    <button type="button" class="report-button" data-bs-toggle="modal" data-bs-target="#staticBackdrop"  data-toggle="tooltip" data-placement="bottom" title="Report">
                        <i class="fa-solid fa-ban" style="color: red;"></i>
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false"
                        tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="staticBackdropLabel">Report</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                </div>
                                <form action="{% url 'questions:report' question.id %}" method="POST">
                                    {% csrf_token %}
                                    <div class="modal-body">
                                        <input type="hidden" name="obj_type" value="q">
                                        <textarea class="form-control" name="report_text" aria-label="With textarea"
                                            placeholder="Author used abusive language..." required></textarea>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary"
                                            data-bs-dismiss="modal">Close</button>
                                        <button type="submit" name="id" value={{question.id}}
                                            class="btn btn-danger">Report</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    &nbsp; &nbsp;

                    <!-- tags associated with the question -->
                    {% for tag in question.tags.all %}
                    {% if tag in user.favouriteTags.all %}
                    <a class="btn btn-success" style="padding: 0px 8px;" href="{% url 'home:tags' tagname=tag.name%}"
                        class="tag_questions">{{tag.name}}</a>
                    {% else %}
                    <a class="btn btn-light" style="padding: 0px 8px; background-color: rgb(255, 227, 189);"
                        href="{% url 'home:tags' tagname=tag.name%}" class="tag_questions">{{tag.name}}</a>
                    {% endif %}
                    {% endfor %}
                </span>

                <!-- question author and publishing date -->
                <div class="text-right" style="position: absolute; right: 16px; color: rgb(94, 94, 94);">Asked by
                    {% if question.get_author_name == 'Anonymous User' %}
                    someone
                    {% else %}
                    <a style="text-decoration: none;" href="{% url 'users:view_user' question.author.id %}">
                        <img src="{{question.author.profile_image.url}}" width="20" height="20"
                            style="border-radius: 50%;">
                        {{question.author.username}}</a>
                    {% endif %}
                    on {{question.pub_date}}
                </div>
            </div>
        </div>
    </div>
    <br />
    {%endfor%}
    {% else %}
    <h2>
        {% block empty_message %}
        No questions to display.
        {% endblock %}
    </h2>
    {% endif %}
</div>

<script>
    $(document).ready(function () {
        // bookmark and follow buttons
        $(".follow-bookmark-form").find(':button').click(function (e) {
            var form = $(this).closest('form');
            var dataString = form.serializeArray();
            dataString.push({ name: 'action', value: $(this).val() });
            $.ajax({
                type: "POST",
                url: "{% url 'questions:follow_bookmark' %}",
                data: dataString,
                success: function (data) {
                    var result = JSON.parse(data);
                    if (result['status'] == 'followed') {
                        form.find('.follow i').removeClass("fa-regular").addClass("fa-solid");
                    }
                    else if (result['status'] == 'bookmarked') {
                        form.find('.bookmark i').removeClass("fa-regular").addClass("fa-solid");
                    }
                    else if (result['status'] == 'unfollowed') {
                        form.find('.follow i').removeClass("fa-solid").addClass("fa-regular");
                    }
                    else {
                        form.find('.bookmark i').removeClass("fa-solid").addClass("fa-regular");
                    }
                },
                error: function () {
                    alert("error");
                }
            });
            e.preventDefault();
        });
    });
</script>
{% block script %}

{% endblock %}
{% endblock %}

{% block insert_right_bar %}
<br> <br> <br>

<!-- favourite and popular tags list -->
<div class="fav-tags" style="box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset, 0 0 8px rgba(146, 146, 146, 0.6);">
    <div class="tags-box">Favourite Tags
        <a href="{% url 'users:addtags' %}" style="position: absolute; right: 28px; font-size: 15px;">Manage</a>
    </div>
    <div style="padding: 12px;">
        {% for tag in user.favouriteTags.all %}
        <a class="btn btn-success" style="padding: 0px 8px; margin: 3px 0px;"
            href="{% url 'home:tags' tagname=tag.name%}" class="tag_questions">{{tag.name}}
        </a>
        {% endfor %}
    </div>
</div>
<br>
<div class="popular-tags" style="box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset, 0 0 8px rgba(146, 146, 146, 0.6);">
    <div class="tags-box">Popular Tags</div>
    <div style="padding: 12px;">
        {% for tag in pop_tags %}
        {% if tag in user.favouriteTags.all %}
        <a class="btn btn-success" style="padding: 0px 8px; margin: 3px 0px;"
            href="{% url 'home:tags' tagname=tag.name%}" class="tag_questions">{{tag.name}}
        </a>
        {% else %}
        <a class="btn btn-light" style="padding: 0px 8px; background-color: rgb(255, 227, 189);"
            href="{% url 'home:tags' tagname=tag.name%}" class="tag_questions">{{tag.name}}
        </a>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

implementation/MindHive/templates/search_results.html
{{error}}

{% if posts %}
    <center> 
        <h1> Search Result Found </h1>
    </center>
    <br/>
{% for post in posts %}
    {{post}}<br/>
{%endfor%}
    {%else%}
    <center><h1>nothing found</h1></center>
{%endif%}