implementation/MindHive/MindHive/urls.py
# MindHive URL Configuration
# The `urlpatterns` list routes URLs to views.

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views


# urlpatterns to match the urls with the views
urlpatterns = [
    path('', views.HomePage.as_view(), name='index'),          # index page
    path('admin/', admin.site.urls),                           # admin page
    path('questions/', include('questions.urls',
         namespace='questions')),                              # questions app urls
    path('users/', include('users.urls', namespace='users')),  # users app urls
    path('home/', include('home.urls', namespace='home'))      # home app urls
]

# add the media files to the urlpatterns
urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

implementation/MindHive/home/urls.py
from django.urls import path
from . import views


# define the namespace for the below urls
app_name='home'

urlpatterns = [
    path('', views.view, name='view_home'),                              # home page
    path('questions', views.allQuestionsView, name='view_questions'),    # all questions page
    path('search_results', views.search_results, name='search_results'), # search results page
    path('following/', views.folView, name='following'),                 # following page
    path('bookmarks/', views.bookView, name='bookmarks'),                # bookmarks page
    path('tags/<tagname>', views.tagView, name='tags'),                  # tag questions page
    path('authorQuestions', views.autQues, name='authorQuestions'),         # author questions page
    path('<int:user_id>/questions', views.otautQues, name='otherauthorQuestions') ,      # author questions page
]

implementation/MindHive/users/urls.py
# declare the various endpoints of users/
from django.urls import path, include
from .views import UserEditView
from . import views
from django.urls import re_path
from django.contrib.auth import views as auth_views
# from django.conf.urls import re_path

app_name = 'users'

urlpatterns = [
    # eg: /users/1/
    path('', views.testview, name='testview'),
    # path('', include('django.contrib.auth.urls')) ,
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',
        views.signup, name='signup'),
    path('<int:pk>', views.profile, name='view_user'),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html',email_template_name='users/password_reset_email.html',success_url='/users/password_reset_done/'), name='reset_password'),
    path('password_reset_done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_sent.html')),
    path('password_reset_confirm/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_form.html',success_url='/users/password_reset_complete/'), name='password_reset_confirm'),
    path('password_reset_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_done.html')),
    path('edit/', UserEditView.as_view(), name='edit_users'),
    path('addtags/',views.addTagsView.as_view(), name='addtags'),
    path('notifications/', views.notifs_display, name='notifs'),
    path('users/', views.users_list_view, name='users_list'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate')
]

implementation/MindHive/users/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.contrib.auth.models import BaseUserManager, AbstractUser

# declare the userInfo model manager

class EmailValidator(RegexValidator):
    regex = '@iitk.ac.in$'
    message = 'Enter a valid email address'
    code = 'invalid_email'

class UserInfoManager(BaseUserManager):
    # function for creating a normal user
    def create_user(self, email, username, name, password,roll_no=None, ):
        if not email:
            raise ValueError('User must have an email address')

        user = self.model(
            email = self.normalize_email(email),
            username=username,
            
            name=name,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    # function for creating an admin user
    def create_superuser(self, email, username, password, name=None, roll_no=None):
        user = self.create_user(email=email, username=username, name=name,
                                 password=password)
        user.is_superuser = True
        user.is_staff = True

        user.save(using=self._db)

        return user

# declare the main User model by inheriting the AbstractUser model of Django
class User(AbstractUser):

    username = models.CharField(max_length=25,blank=False,unique=True)
    email = models.EmailField(
        verbose_name='email address',
        max_length=50,
        unique=True,
        blank=False,
        validators=[EmailValidator()]
    )

    name = models.CharField(max_length=30, blank=True, null=True)

    profile_image = models.ImageField(upload_to='profile_image', default='default.jpg')
    blocked = models.BooleanField(default=False)
    followingQuestions = models.ManyToManyField(to='questions.Question', related_name='users_following', blank=True)
    bookmarkQuestions = models.ManyToManyField(to='questions.Question', related_name='users_bookmarked', blank=True)
    favouriteTags = models.ManyToManyField(to='tags.Tag', blank=True)

    objects = UserInfoManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username' ]

    def __str__(self):
        return self.username

# model for reporting a question/user
class Report(models.Model):
    report_text = models.CharField(max_length=200)
    reporter = models.ForeignKey(User, on_delete=models.CASCADE)
    reportedUser = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reported')
    reported_on = models.DateTimeField(auto_now_add=True)
    REPORTED_OBJECT_TYPES = (
        ('q', 'Question'),
        ('a', 'Answer'),
        ('c', 'Comment'),
    )
    reportedObjType = models.CharField(max_length=1, choices=REPORTED_OBJECT_TYPES)
    reportedObjQ = models.ForeignKey(to='questions.Question', on_delete=models.CASCADE, null=True, blank=True)
    reportedObjA = models.ForeignKey(to='answers.Answer', on_delete=models.CASCADE, null=True, blank=True)
    reportedObjC = models.ForeignKey(to='comments.Comment', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.report_text

implementation/MindHive/users/forms.py
import sys

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import User


sys.path.append("..")


'''
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
'''


# form for signing up
class UserCreateForm(UserCreationForm):
    email = forms.EmailInput(attrs={'placeholder': 'Email Address'})
    class Meta:
        # declare the approproate fields
        fields = ('username', 'name', 'email', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'name': forms.TextInput(attrs={'placeholder': 'Full Name'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email Address'}),
        }
        # model = get_user_model()
        model = User

    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].label = ''
        self.fields['username'].label = ''
        self.fields['name'].label = ''


# form for editing the username and the profile image
class UpdateUserInfo(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username","profile_image"]
        widgets={
            'username': forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your new user name'}),
        }
        profile_image=forms.ImageField()
        

# form for adding the favourite tags
class addTagsForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['favouriteTags']
        labels = {'favouriteTags': 'Favourite Tags'}
        widgets = {
            'favouriteTags': forms.CheckboxSelectMultiple(attrs={
                'class': 'form-check-input form-check-inline',
                }),
        }
        # favouriteTags = forms.ModelMultipleChoiceField(
        #                 queryset=Tag.objects.all(),
        #                 widget=forms.CheckboxSelectMultiple).

implementation/MindHive/users/views.py
from .models import User
from notifications.models import Notification
from .forms import addTagsForm, UserCreateForm

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.urls import reverse
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
# Create your views here.

User = get_user_model()

# view function for showing the notifications
@login_required(login_url='/users/login')
def notifs_display(request):
    notifs = Notification.objects.filter(receiver__pk = request.user.id)
    # print(Notification.objects.all()[0].receiver)
    print(len(notifs))
    Notification.objects.filter(receiver__pk=request.user.id).delete()
    print("deleted notifications")
    return render(request, 'users/notifs.html', {'notifications': notifs})

# class-based view for signing up
# class SignUp(CreateView):
#     form_class = UserCreateForm
#     success_url = reverse_lazy('users:login')
#     template_name = 'users/sign_up.html'




def signup(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your MindHive account.'
            message = render_to_string('users/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = UserCreateForm()
    return render(request, 'users/sign_up.html', {'form': form})# class-based view to add favourite tags

def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        # login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')

class addTagsView(LoginRequiredMixin, UpdateView):
    model = User
    form_class= addTagsForm
    # fields = ['favouriteTags']
    template_name = 'users/addtags.html'
    login_url = '/users/login'
    def get_object(self):
        return self.request.user
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('home:view_home', )

# view function to view profile
def profile(request,pk):
    usr = User.objects.get(pk=pk)
    if request.user.is_authenticated:
        return render(request, 'homepage.html', {'usr': usr, 'viewer': request.user})
    else:
        return render(request, 'homepage.html', {'usr': usr})

def testview(request):
    return HttpResponse('<h1>Test page</h1>')

def users_list_view(request):
    users = []
    cnt = 0
    user_row = []
    for user in User.objects.all():
        user_row.append(user)
        cnt += 1
        if cnt % 3 == 0 or cnt == User.objects.count():
            users.append(user_row)
            user_row = []
    return render(request, 'users/users_list.html', {'users': users})

# view function to edit the user info
class UserEditView(LoginRequiredMixin, UpdateView):
    model = User
    fields=["username","profile_image"]
    template_name = "users/edit_profile.html"
    login_url = '/users/login/'
    # form = Updateuserinfo(request.POST)
    def get_object(self):
        return self.request.user
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('users:view_user', kwargs={'pk': self.object.id})

implementation/MindHive/users/templates/users/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

implementation/MindHive/users/templates/users/addtags.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block insert_title %}
    Add Favourite Tags - MindHive
{% endblock %}

{% block insert_content %}
<section>
<div class="form-group" >
    <form method="post">{% csrf_token %}
        {{ form.media }}
        {{ form.author.as_hidden }}
        {{ form|crispy }}
        <input type="submit" value="Save">
    </form>
</div>
</section>
{% endblock %}

implementation/MindHive/users/templates/users/edit_profile.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}

{% block insert_title %}
    Edit Profile - MindHive
{% endblock %}

{%block insert_content%}
<div class="form-group" >
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{form|crispy }}
        <button class="btn btn-secondary">Update Profile</button>
    </form>
</div>
{% endblock %}

implementation/MindHive/users/templates/users/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Login - MindHive</title>

  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  <link href="{% static 'css/master.css'%}" rel="stylesheet" />
</head>

<body>
  <!-- Header-->
  <header class="text-white" style="background-color: #412c49;">
    <div class="container px-4 text-center">
      <br>
      <h1 class="fw-bolder">
        <a class="title-mindhive" href="{% url 'index' %}" style="color: white;">Welcome to MindHive</a>
      </h1>
      <p class="lead">A QnA platform for the IITK community</p>
      <br>
    </div>
  </header>

  <br>

  <div class="container">
    <p style="color: green; margin: 0;">{{ success }}</p>
    <p style="color: red; margin: 0;">{{ error }}</p>
    {% load bootstrap3 %}

    <div style="padding: 0px 260px;">
      <form class="form-group"
        style="padding: 25px 35px; box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset, 0 0 8px rgba(146, 146, 146, 0.6);"
        id="post_form" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <p class="text-center" style="margin: 0;">
          <input type="submit" value="Login" class="btn btn-primary btn-fill">
        </p>
      </form>
    </div>
    <br>

    <div class="container">
      <p class="text-center">
        <a href="{% url 'users:reset_password' %}">Forgot Password?</a>
      </p>


      <p class="text-center">Don't have an account?
        <a href="{% url 'users:signup' %}">Sign up</a>
      </p>
    </div>
  </div>
</body>

</html>

implementation/MindHive/users/templates/users/notifs.html
{% extends 'base.html' %}

{% block insert_content%}
<div class="container">
  {% if notifications %}
  {% for notifs in notifications %}
    <div class="card" style="padding:5px">
      {{notif.timestamp}}<br>{{notifs.text}}
    </div>
    <hr>
    {% endfor %}

  {% else %}
  <h2>No new notifications</h2>

  </div>
{% endif %}

</div>
{% endblock %}

implementation/MindHive/users/templates/users/password_reset.html
{% load bootstrap3 %}

{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Reset password</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>
<center>
  <header class="text-white" style="background-color: #412c49;">
    <div class="container px-4 text-center">
      <br>
      <h1>Password reset</h1>
      <br>
    </div>
  </header>
  <br>
<div class="container" style="padding: 0px 260px;">
<form class="" method="post" style="padding: 25px 35px; box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset, 0 0 8px rgba(146, 146, 146, 0.6);">
  {% csrf_token %}
  {% bootstrap_form form %}
  <br>
  <input type="submit" class="btn btn-fill btn-primary" name="reset_password_button" value="Reset password">
</form>
</div>
</center>
</body>
</html>

implementation/MindHive/users/templates/users/password_reset_done.html
<h3>Password reset complete</h3>

<p>Your password has been set. You may go ahead and log in now.</p>

<a href="{% url 'users:login' %}">Log in</a>

implementation/MindHive/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

implementation/MindHive/users/templates/users/password_reset_form.html
{% load bootstrap3 %}

{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Reset password</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>

<center>

  <header class="text-white" style="background-color: #412c49;">
    <div class="container px-4 text-center">
      <br>
<h3>Enter new password</h3>
<br>
    </div>
  </header>
<p>Please enter your new password twice so we can verify you typed it in correctly.</p>
<div class="container" style="width: 1000px; padding: 25px 35px; box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset, 0 0 8px rgba(146, 146, 146, 0.6);">
<form method="post">

	{% csrf_token %}
	{{form}}
  <br>
  <br>
	<input type="Submit" name="Update Password" class="btn btn-primary">

</form>
</div>

</center>
</body>
</html>

implementation/MindHive/users/templates/users/password_reset_sent.html
{% load bootstrap3 %}

{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Reset password</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>

<center>
  <h3>Password reset sent</h3>


  <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

  <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
</center>
</body>
</html>

implementation/MindHive/users/templates/users/sign_up.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap3 %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Sign Up - MindHive</title>

  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  <link href="{% static 'css/master.css'%}" rel="stylesheet" />
</head>

<body>
  <!-- Header-->
  <header class="text-white" style="background-color: #412c49;">
    <div class="container px-4 text-center">
      <br>
      <h1 class="fw-bolder">
        <a class="title-mindhive" href="{% url 'index' %}" style="color: white;">Welcome to MindHive</a>
      </h1>
      <p class="lead">A QnA platform for the IITK community</p>
      <br>
    </div>
  </header>

  <br>

  <div class="container" style="padding: 0px 260px;">
    <form class="form-group"
      style="padding: 25px 35px; box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset, 0 0 8px rgba(146, 146, 146, 0.6);"
      id="post_form" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <p style="text-align: center; margin: 0;">
        <button type="submit" class="btn btn-primary">Sign Up</button>
      </p>
    </form>
  </div>
  <p style="text-align: center; margin: 0;">Already have an account? <a href="{% url 'users:login' %}">Sign in</a></p>

</body>

</html>

implementation/MindHive/users/templates/users/users_list.html
{% extends 'base.html' %}

{% block insert_title %}
Users - MindHive
{% endblock %}

{% block insert_content %}
<h1 class="container">
    {% block heading %}
    Users
    {% endblock %}
</h1>

<br>

<div class="container">
    {%for user_row in users%}
    <div class="d-flex justify-content-between">
        {%for user in user_row%}
        <a class="col" href="{% url 'users:view_user' user.id %}" style="text-decoration: none; box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset, 0 0 8px rgba(146, 146, 146, 0.6); max-width: 32%;">
            <div class="d-flex flex-row user-box">
                <div class="d-flex flex-column justify-content-center" style="padding: 5px;">
                    <img src="{{user.profile_image.url}}" width="50" height="50" style="border-radius: 50%;">
                </div>
                <div class="d-flex flex-column w-100" style="padding: 10px;">
                    {{user.name}} <br>
                    {{user.email}} <br>

                </div>
            </div>
        </a>
        {%endfor%}
    </div>
    <br />
    {%endfor%}
</div>
{% endblock %}